# Generated by Django 4.2.7 on 2025-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0016_auto_20220323_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumenttickets',
            name='aadhar_card_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_uploads/'),
        ),
        migrations.AddField(
            model_name='monumenttickets',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monumenttickets',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monumenttickets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monumenttickets',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tickett',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
