# Generated by Django 4.2.7 on 2025-07-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0017_monumenttickets_aadhar_card_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumenttickets',
            name='count_senior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monumenttickets',
            name='price_senior',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
    ]
