# Generated by Django 4.2.7 on 2025-07-27 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrscan', '0018_monumenttickets_count_senior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('north', 'North India'), ('south', 'South India'), ('east', 'East India'), ('west', 'West India'), ('northeast', 'Northeast India'), ('central', 'Central India')], max_length=50)),
                ('description', models.TextField()),
                ('historical_significance', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('opening_hours', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('historical', 'Historical Monument'), ('religious', 'Religious Site'), ('natural', 'Natural Wonder'), ('museum', 'Museum'), ('palace', 'Palace/Fort'), ('temple', 'Temple'), ('beach', 'Beach'), ('hill_station', 'Hill Station'), ('wildlife', 'Wildlife Sanctuary'), ('cultural', 'Cultural Site')], max_length=50)),
                ('architectural_style', models.CharField(blank=True, max_length=100)),
                ('unesco_heritage', models.BooleanField(default=False)),
                ('experience_type', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('spiritual', 'Spiritual'), ('nature', 'Nature'), ('heritage', 'Heritage'), ('photography', 'Photography'), ('relaxation', 'Relaxation')], max_length=50)),
                ('accessibility', models.CharField(choices=[('easy', 'Easy Access'), ('moderate', 'Moderate Access'), ('difficult', 'Difficult Access')], max_length=50)),
                ('duration_recommended', models.CharField(max_length=50)),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('recommendation_score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('reason', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrscan.tourdestination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommendation_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('preferred_categories', models.JSONField(default=list)),
                ('preferred_regions', models.JSONField(default=list)),
                ('preferred_experience_types', models.JSONField(default=list)),
                ('budget_range', models.CharField(choices=[('budget', 'Budget (₹0-500)'), ('moderate', 'Moderate (₹500-2000)'), ('premium', 'Premium (₹2000+)')], default='moderate', max_length=20)),
                ('accessibility_preference', models.CharField(choices=[('easy', 'Easy Access Only'), ('any', 'Any Accessibility')], default='any', max_length=20)),
                ('crowd_preference', models.CharField(choices=[('low', 'Avoid Crowds'), ('any', 'Any Crowd Level')], default='any', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='tourdestination',
            index=models.Index(fields=['category'], name='qrscan_tour_categor_99900e_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdestination',
            index=models.Index(fields=['state'], name='qrscan_tour_state_510a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdestination',
            index=models.Index(fields=['region'], name='qrscan_tour_region_1b3072_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdestination',
            index=models.Index(fields=['unesco_heritage'], name='qrscan_tour_unesco__fd6141_idx'),
        ),
        migrations.AddField(
            model_name='destinationreview',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='qrscan.tourdestination'),
        ),
        migrations.AddField(
            model_name='destinationreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrecommendation',
            unique_together={('session_key', 'destination')},
        ),
    ]
